name: Sync developing branches

on:
  push:
    branches:
        - 'main'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
  
      - name: Set up Git user
        run: |
          git config user.name "JVmano"
          git config user.email "jdefreitasmelo@gmail.com"

      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://JVmano:${{ secrets.MERGE_AUTOMATION_TOKEN  }}@github.com/${{ github.repository }}.git
  
      - name: Sync staging branch from main
        run: |
          git fetch origin
          git checkout staging
          git reset --hard origin/staging
          git merge origin/main
          git push origin staging || {
            echo "Push failed. The remote branch might have new commits."
            echo "Pulling latest changes and trying again..."
            git pull --rebase origin staging
            git merge origin/main
            git push origin staging
          }